/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author Ramziz
 */
public class FormLoginMhs extends javax.swing.JFrame {

    Connection conn;
    Statement stm;
    ResultSet rs;
    public FormLoginMhs() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        conn = DB.con;
        stm = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNrp = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        lbexitmhs = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLoginMhs = new javax.swing.JButton();
        btberalihadmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfNrp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfNrp.setBorder(null);
        tfNrp.setOpaque(false);
        getContentPane().add(tfNrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 210, 20));

        tfPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfPassword.setBorder(null);
        tfPassword.setOpaque(false);
        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 200, 30));

        lbexitmhs.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbexitmhs.setForeground(new java.awt.Color(255, 255, 255));
        lbexitmhs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbexitmhs.setText("EXIT");
        lbexitmhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbexitmhsMouseClicked(evt);
            }
        });
        getContentPane().add(lbexitmhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 60, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/2.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 510));

        btnLoginMhs.setText("Login");
        btnLoginMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginMhsActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoginMhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 305, 300, 40));

        btberalihadmin.setText("Beralih ke Admin");
        btberalihadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btberalihadminActionPerformed(evt);
            }
        });
        getContentPane().add(btberalihadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 365, 270, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btberalihadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btberalihadminActionPerformed
        // TODO add your handling code here:
        FormLogin loginAdmin = new FormLogin();
        loginAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btberalihadminActionPerformed

    private void btnLoginMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginMhsActionPerformed
        // TODO add your handling code here:
        try{
            rs = stm.executeQuery("SELECT * FROM mahasiswa WHERE NRP='"+tfNrp.getText()+"' AND password='"+tfPassword.getText()+"'");
            if (rs.next()){
                if(tfNrp.getText().equals(rs.getString("NRP"))
                    && tfPassword.getText().equals(rs.getString("password"))) {
                    LihatData menu = new LihatData();
                    menu.setData(tfNrp.getText());
                    menu.setVisible(true);
                    this.dispose();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Maaf, kombinasi" +
                    " Nrp dan Password anda salah");
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnLoginMhsActionPerformed

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void lbexitmhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbexitmhsMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lbexitmhsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLoginMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLoginMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLoginMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLoginMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLoginMhs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btberalihadmin;
    private javax.swing.JButton btnLoginMhs;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbexitmhs;
    private javax.swing.JTextField tfNrp;
    private javax.swing.JPasswordField tfPassword;
    // End of variables declaration//GEN-END:variables
}
