
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class LihatData extends javax.swing.JFrame {
    public Connection conn;
    public ResultSet rs;
    public Statement stm;
    String sql;
    /**
     * Creates new form LihatData
     */
    public LihatData() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        conn = DB.con;
        stm = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentPanel = new javax.swing.JPanel();
        panelMahasiswa = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfCari = new javax.swing.JTextField();
        btnTampil = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_image = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfNrp = new javax.swing.JLabel();
        tfNama = new javax.swing.JLabel();
        tfProdi = new javax.swing.JLabel();
        tfStatus = new javax.swing.JLabel();
        tfJk = new javax.swing.JLabel();
        tfAgama = new javax.swing.JLabel();
        tfAlamat = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        tfPembimbing = new javax.swing.JLabel();
        tfEmail = new javax.swing.JLabel();
        tfNoHp = new javax.swing.JLabel();
        tfNamaAyah = new javax.swing.JLabel();
        tfNoKtpAyah = new javax.swing.JLabel();
        tfIbu = new javax.swing.JLabel();
        tfOrtu = new javax.swing.JLabel();
        tfAlamatOrtu = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        panelJadwal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuJadwal = new javax.swing.JMenuItem();
        menuKeluar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        parentPanel.setLayout(new java.awt.CardLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Informasi Mahasiswa");

        jLabel5.setText("Cari dengan NRP");

        btnTampil.setText("Lihat");
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });

        jLabel7.setText("NRP");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_image.setText("Foto Diri");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_image, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_image, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
        );

        jLabel8.setText("Nama");

        jLabel9.setText("Prodi");

        jLabel10.setText("Status Masuk");

        jLabel11.setText("Jenis Kelamin");

        jLabel12.setText("Agama");

        jLabel13.setText("Alamat");

        tfNrp.setText("Data");

        tfNama.setText("Data");

        tfProdi.setText("Data");

        tfStatus.setText("Data");

        tfJk.setText("Data");

        tfAgama.setText("Data");

        tfAlamat.setText("Data");

        jLabel21.setText("Email");

        jLabel22.setText("No HP");

        jLabel23.setText("Nama Ayah");

        jLabel24.setText("No KTP Ayah");

        jLabel25.setText("Nama Ibu");

        jLabel26.setText("Telepon Orang Tua");

        jLabel27.setText("Alamat Orang Tua");

        jLabel28.setText("Pembimbing");

        tfPembimbing.setText("Data");

        tfEmail.setText("Data");

        tfNoHp.setText("Data");

        tfNamaAyah.setText("Data");

        tfNoKtpAyah.setText("Data");

        tfIbu.setText("Data");

        tfOrtu.setText("Data");

        tfAlamatOrtu.setText("Data");

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMahasiswaLayout = new javax.swing.GroupLayout(panelMahasiswa);
        panelMahasiswa.setLayout(panelMahasiswaLayout);
        panelMahasiswaLayout.setHorizontalGroup(
            panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(panelMahasiswaLayout.createSequentialGroup()
                        .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMahasiswaLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelMahasiswaLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(75, 75, 75)
                                        .addComponent(tfNrp))
                                    .addGroup(panelMahasiswaLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(68, 68, 68)
                                        .addComponent(tfNama))
                                    .addGroup(panelMahasiswaLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(71, 71, 71)
                                        .addComponent(tfProdi))
                                    .addGroup(panelMahasiswaLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(31, 31, 31)
                                        .addComponent(tfStatus))
                                    .addGroup(panelMahasiswaLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(32, 32, 32)
                                        .addComponent(tfJk))
                                    .addGroup(panelMahasiswaLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(62, 62, 62)
                                        .addComponent(tfAgama))
                                    .addGroup(panelMahasiswaLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(62, 62, 62)
                                        .addComponent(tfAlamat))
                                    .addGroup(panelMahasiswaLayout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addGap(39, 39, 39)
                                        .addComponent(tfPembimbing))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMahasiswaLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMahasiswaLayout.createSequentialGroup()
                                .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMahasiswaLayout.createSequentialGroup()
                                .addComponent(btnTampil)
                                .addGap(41, 41, 41)))
                        .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfAlamatOrtu)
                            .addComponent(tfOrtu)
                            .addComponent(tfIbu)
                            .addComponent(tfNoKtpAyah)
                            .addComponent(tfNamaAyah)
                            .addComponent(tfNoHp)
                            .addComponent(tfEmail))))
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMahasiswaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClear)
                .addGap(45, 45, 45))
        );
        panelMahasiswaLayout.setVerticalGroup(
            panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTampil))
                .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelMahasiswaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMahasiswaLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfNrp)
                            .addComponent(jLabel21)
                            .addComponent(tfEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfNama)
                            .addComponent(jLabel22)
                            .addComponent(tfNoHp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tfProdi)
                            .addComponent(jLabel23)
                            .addComponent(tfNamaAyah))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfStatus)
                            .addComponent(jLabel24)
                            .addComponent(tfNoKtpAyah))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tfJk)
                            .addComponent(jLabel25)
                            .addComponent(tfIbu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tfAgama)
                            .addComponent(jLabel26)
                            .addComponent(tfOrtu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tfAlamat)
                            .addComponent(jLabel27)
                            .addComponent(tfAlamatOrtu))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(tfPembimbing))
                .addGap(18, 18, 18)
                .addComponent(btnClear)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        parentPanel.add(panelMahasiswa, "card3");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Jadwal Mahasiswa");

        jLabel2.setText("NRP Mahasiswa");

        jButton1.setText("Tampil");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Kelas", "Nama Mata Kuliah", "Kelas", "Waktu", "Ruang", "Pengajar"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("Menampilkan Jadwal:");

        javax.swing.GroupLayout panelJadwalLayout = new javax.swing.GroupLayout(panelJadwal);
        panelJadwal.setLayout(panelJadwalLayout);
        panelJadwalLayout.setHorizontalGroup(
            panelJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJadwalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                    .addGroup(panelJadwalLayout.createSequentialGroup()
                        .addGroup(panelJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(panelJadwalLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelJadwalLayout.setVerticalGroup(
            panelJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJadwalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        parentPanel.add(panelJadwal, "panelJadwal");

        jMenu1.setText("Menu");

        jMenuItem1.setText("Mahasiswa");
        jMenu1.add(jMenuItem1);

        menuJadwal.setText("Jadwal");
        menuJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuJadwalActionPerformed(evt);
            }
        });
        jMenu1.add(menuJadwal);

        jMenuBar1.add(jMenu1);

        menuKeluar.setText("Keluar");
        menuKeluar.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuKeluarMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuKeluar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuKeluarMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuKeluarMenuSelected
        // TODO add your handling code here:
        MainMenu main = new MainMenu();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuKeluarMenuSelected

    private void menuJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuJadwalActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) parentPanel.getLayout();
        cl.show(parentPanel, "panelJadwal");
    }//GEN-LAST:event_menuJadwalActionPerformed

    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilActionPerformed
        // TODO add your handling code here:
        String nrp = tfCari.getText();
        if(!"".equals(nrp)){
            try{
                rs = stm.executeQuery("SELECT * FROM mahasiswa INNER JOIN dosen ON mahasiswa.NIP_DOSEN = dosen.NIP_DOSEN WHERE NRP = '"+nrp+"'");
                rs.next();
                tfNrp.setText(rs.getString("NRP"));
                tfNama.setText(rs.getString("NAMA_MAHASISWA"));
                tfProdi.setText(rs.getString("PRODI"));
                tfStatus.setText(rs.getString("STATUS_MASUK"));
                tfJk.setText(rs.getString("JENIS_KELAMIN"));
                tfAgama.setText(rs.getString("AGAMA"));
                tfAlamat.setText(rs.getString("ALAMAT"));
                tfPembimbing.setText(rs.getString("NAMA_DOSEN"));
                tfEmail.setText(rs.getString("EMAIL"));
                tfNoHp.setText(rs.getString("NO_HP"));
                tfNamaAyah.setText(rs.getString("NAMA_AYAH"));
                tfNoKtpAyah.setText(rs.getString("NOMOR_KTP_AYAH"));
                tfIbu.setText(rs.getString("NAMA_IBU"));
                tfOrtu.setText(rs.getString("TELEPON_ORANG_TUA"));
                tfAlamatOrtu.setText(rs.getString("ALAMAT_ORANG_TUA"));
                BufferedImage img = ImageIO.read(new File(rs.getString("link_foto")));
                Image resizedImage = img.getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(resizedImage);
                lbl_image.setText("");
                lbl_image.setIcon(icon);
            }catch(SQLException | IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Kolom harus diisi");
        }
    }//GEN-LAST:event_btnTampilActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        tfNrp.setText("");
        tfNama.setText("");
        tfProdi.setText("");
        tfStatus.setText("");
        tfJk.setText("");
        tfAgama.setText("");
        tfAlamat.setText("");
        tfPembimbing.setText("");
        tfEmail.setText("");
        tfNoHp.setText("");
        tfNamaAyah.setText("");
        tfNoKtpAyah.setText("");
        tfIbu.setText("");
        tfOrtu.setText("");
        tfAlamatOrtu.setText("");
        lbl_image.setIcon(null);
        lbl_image.setText("Foto Diri");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LihatData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LihatData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LihatData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LihatData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LihatData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnTampil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JMenuItem menuJadwal;
    private javax.swing.JMenu menuKeluar;
    private javax.swing.JPanel panelJadwal;
    private javax.swing.JPanel panelMahasiswa;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JLabel tfAgama;
    private javax.swing.JLabel tfAlamat;
    private javax.swing.JLabel tfAlamatOrtu;
    private javax.swing.JTextField tfCari;
    private javax.swing.JLabel tfEmail;
    private javax.swing.JLabel tfIbu;
    private javax.swing.JLabel tfJk;
    private javax.swing.JLabel tfNama;
    private javax.swing.JLabel tfNamaAyah;
    private javax.swing.JLabel tfNoHp;
    private javax.swing.JLabel tfNoKtpAyah;
    private javax.swing.JLabel tfNrp;
    private javax.swing.JLabel tfOrtu;
    private javax.swing.JLabel tfPembimbing;
    private javax.swing.JLabel tfProdi;
    private javax.swing.JLabel tfStatus;
    // End of variables declaration//GEN-END:variables
}
